# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placename', models.CharField(default=b'placename', max_length=140)),
                ('placecity', models.CharField(default=b'somecity', max_length=100)),
                ('lat', models.DecimalField(decimal_places=10, max_digits=20)),
                ('lng', models.DecimalField(decimal_places=10, max_digits=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
