# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 21:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=b'Username', max_length=140)),
                ('placemention', models.TextField(default=b'SOME STRING', max_length=140)),
                ('lat', models.DecimalField(decimal_places=15, max_digits=20)),
                ('lng', models.DecimalField(decimal_places=15, max_digits=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('placeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Place')),
                ('placeinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placeinfo', to='places.Place')),
            ],
        ),
        migrations.AddField(
            model_name='hashtag',
            name='mention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='mentions.Mention'),
        ),
        migrations.AlterUniqueTogether(
            name='hashtag',
            unique_together=set([('mention', 'tagname')]),
        ),
    ]
