# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 21:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0001_initial'),
        ('mentions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reputation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorname', models.CharField(default=b'Authorname', max_length=140)),
                ('value', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mention', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mentions.Mention')),
                ('placeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Place')),
            ],
        ),
    ]
